CREATE TABLE entregas (
    id bigint not null generated by default as identity,
    data_pedido timestamp with time zone not null,
    data_finalizacao timestamp with time zone,
    status character varying(20) not null,
    id_cliente bigint not null,

    PRIMARY KEY (id),
    FOREIGN KEY (id_cliente) REFERENCES clientes (id)
);